import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Search, SlidersHorizontal, X, Star, Download, Film, Camera, LogOut, Check, Aperture, Lock, MessageCircle } from 'lucide-react';
import { supabase } from './supabase';
import { demoAssets } from './demo';
import './style.css';

const categories = ['Všechny styly','Filmové','Příroda','Lifestyle','Cestování','Vintage'];
function App() {
  const [session,setSession] = useState(null), [ready,setReady] = useState(!supabase);
  const [assets,setAssets] = useState(supabase ? [] : demoAssets), [ratings,setRatings] = useState([]);
  const [type,setType] = useState('all'), [category,setCategory] = useState(categories[0]), [query,setQuery] = useState(''), [sort,setSort] = useState('new');
  const [auth,setAuth] = useState(null), [selected,setSelected] = useState(null), [error,setError] = useState(''), [loading,setLoading] = useState(false);
  const [refresh,setRefresh] = useState(0);
  useEffect(()=> {
    if (!supabase) return;
    let active = true;
    supabase.auth.getSession().then(({data,error})=>{if(active){setSession(data.session);setReady(true);if(error)setError('Nepodařilo se ověřit přihlášení.');}});
    const {data:{subscription}} = supabase.auth.onAuthStateChange((_event,value)=>{setSession(value);setReady(true);setSelected(null);});
    return ()=>{active=false;subscription.unsubscribe();};
  },[]);
  useEffect(()=> {
    if (!supabase) return;
    if (!session) {setAssets([]);setRatings([]);return;}
    let active=true;setLoading(true);setError('');
    Promise.all([supabase.from('assets').select('*').order('created_at',{ascending:false}),supabase.from('ratings').select('asset_id,score,user_id')]).then(([a,r])=>{
      if(!active)return;setLoading(false);
      if(a.error||r.error){setError('Katalog se nepodařilo načíst. Zkontroluj připojení a databázové schéma.');return;}
      setAssets(a.data);setRatings(r.data);
    });return ()=>{active=false;};
  },[session,refresh]);
  useEffect(()=>{if(!auth&&!selected)return;const listener=e=>{if(e.key==='Escape'){setAuth(null);setSelected(null);}};document.addEventListener('keydown',listener);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',listener);document.body.style.overflow=previous;};},[auth,selected]);
  const stats=id=>{const rows=ratings.filter(r=>r.asset_id===id);return {count:rows.length,average:rows.length?rows.reduce((sum,r)=>sum+r.score,0)/rows.length:0};};
  const visible=assets.filter(a=>(type==='all'||a.kind===type)&&(category===categories[0]||a.category===category)&&`${a.title} ${a.description} ${a.software}`.toLocaleLowerCase('cs').includes(query.toLocaleLowerCase('cs'))).sort((a,b)=>sort==='rating'?stats(b.id).average-stats(a.id).average:sort==='name'?a.title.localeCompare(b.title,'cs'):new Date(b.created_at)-new Date(a.created_at));
  async function logout(){const {error}=await supabase.auth.signOut();if(error)setError('Odhlášení se nezdařilo. Zkus to znovu.');}
  return <><header className="header"><a className="brand" href="#"><Aperture size={29}/> FRAME<span className="brand-dot">.</span></a><nav aria-label="Hlavní navigace"><a className="nav-active" href="#catalog">Knihovna</a><a href="#how">Jak to funguje</a></nav><div className="account">{session?<><span className="email">{session.user.email}</span><button className="text-button" onClick={logout} title="Odhlásit se"><LogOut size={18}/><span>Odhlásit</span></button></>:<><button className="text-button" onClick={()=>setAuth('login')}>Přihlásit se</button><button className="button small" onClick={()=>setAuth('signup')}>Vytvořit účet <ArrowUpRight size={16}/></button></>}</div></header>
  <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> PRO TVŮRCE. ZDARMA.</div><h1>Tvůj příběh.<br/>Nové <em>barvy.</em></h1><p>Objev LUTy a presety, které dají tvým fotkám<br className="desktop-break"/> a videím vlastní charakter. Tvoř, sdílej a inspiruj.</p><a className="button hero-button" href="#catalog">Prozkoumat knihovnu <ArrowRight size={18}/></a><div className="hero-note"><span><Check size={14}/> 100 % zdarma</span><span><Check size={14}/> Pro foto i video</span></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=90" alt="Horská krajina s domkem u klidného jezera"/><div className="image-grain"/><span className="image-caption">MALÁ ZMĚNA. VELKÁ ATMOSFÉRA.</span><div className="image-label"><span className="live-dot"/> THE GOLDEN LOOK <span>01 / 06</span></div></div></section>
  <div className="feature-strip"><span><Film size={19}/> LUTy pro tvá videa</span><span><Camera size={19}/> Presety pro tvé fotografie</span><span><MessageCircle size={19}/> Komunita, která tvoří</span><span><Download size={19}/> Stažení bez poplatků</span></div>
  <section id="catalog" className="catalog"><div className="section-top"><div><div className="eyebrow muted">NAJDI SVŮJ STYL</div><h2>Knihovna inspirace<span>.</span></h2><p>Jeden klik může změnit celý příběh.</p></div><span className="item-count">{assets.length} {supabase?'položek v knihovně':'ukázkových položek'}</span></div>
  {!supabase&&<div className="notice">Ukázkový režim · Pro registraci, stahování a komunitní funkce připoj Supabase podle README.</div>}
  <div className="toolbar"><div className="tabs" role="group" aria-label="Typ obsahu">{[['all','Vše'],['lut','Video LUTy'],['preset','Foto presety']].map(([value,label])=><button key={value} className={type===value?'active':''} onClick={()=>setType(value)}>{value==='lut'?<Film size={16}/>:value==='preset'?<Camera size={16}/>:null}{label}</button>)}</div><label className="search"><Search size={18}/><input aria-label="Hledat v knihovně" placeholder="Hledat svůj nový look…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="select-wrap"><SlidersHorizontal size={16}/><select aria-label="Styl" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div>
  <div className="results-top"><span>{visible.length} výsledků</span><label>Řadit podle: <select aria-label="Řazení" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Nejnovější</option><option value="rating">Nejlépe hodnocené</option><option value="name">Názvu</option></select></label></div>
  {error&&<div role="alert" className="notice error">{error}<button onClick={()=>setRefresh(v=>v+1)}>Zkusit znovu</button></div>}
  {!ready||loading?<div className="empty">Načítám knihovnu…</div>:supabase&&!session?<div className="empty locked"><Lock size={30}/><h3>Tvoje další inspirace čeká uvnitř.</h3><p>Přihlas se a získáš přístup ke všem LUTům, presetům a komentářům.</p><button className="button" onClick={()=>setAuth('signup')}>Vytvořit účet zdarma <ArrowRight size={17}/></button></div>:visible.length?<div className="grid">{visible.map(a=>{const s=stats(a.id);return <button className="card" key={a.id} onClick={()=>setSelected(a)}><div className="card-image"><img loading="lazy" src={a.image_url} alt={a.title}/><span className={`badge ${a.kind}`}>{a.kind==='lut'?<Film size={12}/>:<Camera size={12}/>} {a.kind==='lut'?'VIDEO LUT':'FOTO PRESET'}</span>{a.featured&&<span className="featured">Výběr FRAME</span>}<span className="card-open"><ArrowUpRight size={20}/></span></div><div className="card-body"><div className="card-heading"><h3>{a.title}</h3><span className="free">ZDARMA</span></div><p>{a.category} <span>·</span> {a.format}</p><div className="card-bottom"><span className="rating"><Star size={14}/>{s.count?s.average.toFixed(1):'Bez hodnocení'}{s.count>0&&<small>({s.count})</small>}</span><span className="discover">Zobrazit <ArrowRight size={14}/></span></div></div></button>;})}</div>:<div className="empty"><h3>{assets.length?'Tento styl jsme zatím nenašli.':'Knihovna je připravená na první položky.'}</h3><p>{assets.length?'Zkus jiný výraz nebo uprav filtry.':'Přidej LUTy a presety v Supabase do tabulky assets.'}</p>{assets.length>0&&<button className="text-button" onClick={()=>{setQuery('');setCategory(categories[0]);setType('all');}}>Vymazat filtry</button>}</div>}
  </section><section id="how" className="how"><div><div className="eyebrow muted">VÍC TVOŘENÍ. MÉNĚ HLEDÁNÍ.</div><h2>Od inspirace k tvému<br/>novému looku.</h2></div><div className="steps">{[['01','Přidej se','Vytvoř si účet zdarma a otevři celou knihovnu.'],['02','Najdi svůj styl','Vyber LUT pro video nebo preset pro fotografii.'],['03','Stáhni a tvoř','Stáhni soubor z Google Drive. Poděl se o hodnocení a zkušenosti.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section></main>
  <footer><a className="brand" href="#"><Aperture size={23}/> FRAME.</a><p>Barvy spojují. Tvořme společně.</p><span>© {new Date().getFullYear()} FRAME</span></footer>
  {auth&&<AuthModal mode={auth} setMode={setAuth} close={()=>setAuth(null)}/>}
  {selected&&<Detail asset={selected} session={session} close={()=>setSelected(null)} stats={stats(selected.id)} onRating={()=>setRefresh(v=>v+1)}/>}
  </>;
}
function Modal({close,children,label}) {
  const ref=React.useRef(null);
  useEffect(()=>{const previous=document.activeElement;const el=ref.current;el.focus();const trap=e=>{if(e.key!=='Tab')return;const focusable=[...el.querySelectorAll('button,input,textarea,a[href],select')].filter(x=>!x.disabled);if(!focusable.length){e.preventDefault();return;}const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===el)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===el)){e.preventDefault();first.focus();}};el.addEventListener('keydown',trap);return()=>{el.removeEventListener('keydown',trap);previous?.focus();};},[]);
  return <div className="overlay" onClick={e=>{if(e.target===e.currentTarget)close();}}><section ref={ref} tabIndex={-1} className="modal" role="dialog" aria-modal="true" aria-label={label}><button className="close" onClick={close} aria-label="Zavřít"><X size={22}/></button>{children}</section></div>;
}
function AuthModal({mode,setMode,close}) {
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setMessage('');if(!supabase){setMessage('Nejdřív je potřeba připojit Supabase. Návod najdeš v README projektu.');return;}setBusy(true);
    try{let result;if(mode==='signup')result=await supabase.auth.signUp({email,password,options:{data:{display_name:name.trim()},emailRedirectTo:window.location.origin}});else result=await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(mode==='signup'&&!result.data.session)setMessage('Zkontroluj e-mail a potvrď registraci. Potom se můžeš přihlásit.');else close();}catch(err){setMessage(err.code==='invalid_credentials'?'E-mail nebo heslo není správné.':err.code==='email_not_confirmed'?'Nejdřív potvrď registraci odkazem v e-mailu.':err.code==='user_already_exists'?'Tento e-mail už má účet. Přihlas se.':'Akce se nezdařila. Ověř údaje a zkus to znovu.');}finally{setBusy(false);}
  }
  function switchMode(){setMode(mode==='signup'?'login':'signup');setMessage('');}
  return <Modal close={close} label={mode==='signup'?'Registrace':'Přihlášení'}><div className="modal-logo"><Aperture size={32}/></div><div className="eyebrow muted">TVŮJ PROSTOR PRO TVORBU</div><h2>{mode==='signup'?'Začni novou kapitolu.':'Vítej zpátky.'}</h2><p className="modal-intro">Celá knihovna. Nové styly. Jedna kreativní komunita.</p><form onSubmit={submit}>{mode==='signup'&&<label>Jméno v komunitě<input required maxLength={40} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)} placeholder="Jak ti máme říkat?"/></label>}<label>E-mail<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tvuj@email.cz"/></label><label>Heslo<input type="password" required minLength={mode==='signup'?8:1} autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='signup'?'Alespoň 8 znaků':'Tvoje heslo'}/></label>{message&&<p className="notice" role="status">{message}</p>}<button className="button full" disabled={busy}>{busy?'Chvilku strpení…':mode==='signup'?'Vytvořit účet zdarma':'Přihlásit se'}<ArrowRight size={17}/></button></form><p className="auth-switch">{mode==='signup'?'Už máš účet?':'Ještě nemáš účet?'} <button onClick={switchMode}>{mode==='signup'?'Přihlásit se':'Zaregistrovat se'}</button></p></Modal>;
}
function Detail({asset,session,close,stats,onRating}) {
  const [comments,setComments]=useState([]),[text,setText]=useState(''),[score,setScore]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!!supabase);
  useEffect(()=>{if(!supabase||!session)return;let active=true;Promise.all([supabase.from('comments').select('id,user_id,body,created_at,profiles(display_name)').eq('asset_id',asset.id).order('created_at',{ascending:false}),supabase.from('ratings').select('score').eq('asset_id',asset.id).eq('user_id',session.user.id).maybeSingle()]).then(([c,r])=>{if(!active)return;setLoading(false);if(c.error||r.error)setMessage('Komentáře nebo hodnocení se nepodařilo načíst.');else{setComments(c.data);setScore(r.data?.score||0);}});return()=>{active=false;};},[asset.id,session]);
  async function rate(value){if(!supabase||!session){setMessage('Hodnocení je dostupné po připojení Supabase a přihlášení.');return;}setBusy(true);setMessage('');const {error}=await supabase.from('ratings').upsert({asset_id:asset.id,user_id:session.user.id,score:value},{onConflict:'asset_id,user_id'});setBusy(false);if(error)setMessage('Hodnocení se nepodařilo uložit.');else{setScore(value);onRating();}}
  async function comment(e){e.preventDefault();if(!supabase||!session){setMessage('Komentáře jsou dostupné po připojení Supabase a přihlášení.');return;}if(!text.trim())return;setBusy(true);setMessage('');const {data,error}=await supabase.from('comments').insert({asset_id:asset.id,user_id:session.user.id,body:text.trim()}).select('id,user_id,body,created_at,profiles(display_name)').single();setBusy(false);if(error)setMessage('Komentář se nepodařilo uložit.');else{setComments(c=>[data,...c]);setText('');}}
  async function remove(id){setBusy(true);const {error}=await supabase.from('comments').delete().eq('id',id).eq('user_id',session.user.id);setBusy(false);if(error)setMessage('Komentář se nepodařilo smazat.');else setComments(c=>c.filter(x=>x.id!==id));}
  const validDownload=(()=>{try{const u=new URL(asset.download_url);return u.protocol==='https:'&&u.hostname==='drive.google.com';}catch{return false;}})();
  return <Modal close={close} label={asset.title}><img className="detail-image" src={asset.image_url} alt={asset.title}/><div className="eyebrow muted">{asset.kind==='lut'?'VIDEO LUT':'FOTO PRESET'} · {asset.format}</div><h2>{asset.title}</h2><p className="modal-intro">{asset.description}</p><p className="compatibility">Kompatibilita: {asset.software}</p>{session&&validDownload?<a className="button full" href={asset.download_url} target="_blank" rel="noopener noreferrer">Stáhnout z Google Drive <Download size={18}/></a>:<div className="notice">{supabase?'Odkaz na stažení zatím není k dispozici.':'Ukázková položka nemá soubor ke stažení.'}</div>}<div className="detail-rating"><h3>Jak se ti tento styl líbí?</h3><div className="stars" aria-label="Tvoje hodnocení">{[1,2,3,4,5].map(n=><button key={n} disabled={busy} aria-label={`Hodnotit ${n} z 5`} aria-pressed={score===n} onClick={()=>rate(n)}><Star size={25} fill={n<=score?'currentColor':'none'}/></button>)}<span>{stats.count?`${stats.average.toFixed(1)} / 5 · ${stats.count} hodnocení`:'Zatím bez hodnocení'}</span></div></div><h3>Komentáře <span className="muted">({comments.length})</span></h3>{message&&<p className="notice" role="status">{message}</p>}<form onSubmit={comment}><label className="sr-only" htmlFor="comment">Tvůj komentář</label><textarea id="comment" required maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder="Poděl se o svou zkušenost…"/><button className="button small" disabled={busy||!text.trim()}>Přidat komentář <ArrowRight size={15}/></button></form><div className="comments">{loading?<p>Načítám komentáře…</p>:comments.length?comments.map(c=><article key={c.id}><div><strong>{c.profiles?.display_name||'Tvůrce'}</strong><time>{new Date(c.created_at).toLocaleDateString('cs-CZ')}</time></div><p>{c.body}</p>{c.user_id===session?.user.id&&<button className="text-button" disabled={busy} onClick={()=>remove(c.id)}>Smazat</button>}</article>):<p className="muted">Zatím tu je klid. První zkušenost může být tvoje.</p>}</div></Modal>;
}
createRoot(document.getElementById('root')).render(<App/>);
