import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Search, SlidersHorizontal, X, Star, Download, Film, Camera, LogOut, Check, Aperture, Lock, MessageCircle } from 'lucide-react';
import { supabase } from './supabase';
import { demoAssets } from './demo';
import './style.css';
import Admin from './Admin';
import { assetCategories, categoryLabel } from './categories';
import { publicAssetColumns } from './catalog';

const categories = ['All styles', ...assetCategories];
function App() {
  const [session,setSession] = useState(null), [ready,setReady] = useState(!supabase);
  const [assets,setAssets] = useState(supabase ? [] : demoAssets), [ratings,setRatings] = useState([]);
  const [type,setType] = useState('all'), [category,setCategory] = useState(categories[0]), [query,setQuery] = useState(''), [sort,setSort] = useState('new');
  const [auth,setAuth] = useState(null), [selected,setSelected] = useState(null), [error,setError] = useState(''), [loading,setLoading] = useState(false);
  const [refresh,setRefresh] = useState(0);
  const [adminUser,setAdminUser] = useState(null), [showAdmin,setShowAdmin] = useState(false);
  const isAdmin = !!session && adminUser === session.user.id;
  useEffect(() => {
    setAdminUser(null); setShowAdmin(false);
    if (!supabase || !session) return;
    let active = true;
    supabase.rpc('is_admin').then(({ data, error }) => { if (active && !error && data === true) setAdminUser(session.user.id); });
    return () => { active = false; };
  }, [session]);
  useEffect(()=> {
    if (!supabase) return;
    let active = true;
    supabase.auth.getSession().then(({data,error})=>{if(active){setSession(data.session);setReady(true);if(error)setError('Unable to verify your session. Please try again.');}});
    const {data:{subscription}} = supabase.auth.onAuthStateChange((_event,value)=>{setSession(value);setReady(true);if(!value)setSelected(null);});
    return ()=>{active=false;subscription.unsubscribe();};
  },[]);
  useEffect(()=> {
    if (!supabase || !ready) return;
    if (!session) {setSort(previous=>previous==='rating'?'new':previous);setAssets(previous=>previous.map(({download_url,...asset})=>asset));setRatings([]);}
    let active=true;setLoading(true);setError('');
    Promise.all([supabase.from('assets').select(session?'*':publicAssetColumns).order('created_at',{ascending:false}),session?supabase.from('ratings').select('asset_id,score,user_id'):Promise.resolve({data:[],error:null})]).then(([a,r])=>{
      if(!active)return;setLoading(false);
      if(a.error||r.error){setError('Unable to load the library. Please try again later.');return;}
      setAssets(a.data);setRatings(r.data);
    });return ()=>{active=false;};
  },[session,refresh,ready]);
  useEffect(()=>{if(!auth&&!selected)return;const listener=e=>{if(e.key==='Escape'){setAuth(null);setSelected(null);}};document.addEventListener('keydown',listener);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',listener);document.body.style.overflow=previous;};},[auth,selected]);
  const stats=id=>{const rows=ratings.filter(r=>r.asset_id===id);return {count:rows.length,average:rows.length?rows.reduce((sum,r)=>sum+r.score,0)/rows.length:0};};
  const visible=assets.filter(a=>(type==='all'||a.kind===type)&&(category===categories[0]||a.category===category)&&`${a.title} ${a.description} ${a.software}`.toLocaleLowerCase('en').includes(query.toLocaleLowerCase('en'))).sort((a,b)=>sort==='rating'?stats(b.id).average-stats(a.id).average:sort==='name'?a.title.localeCompare(b.title,'en'):new Date(b.created_at)-new Date(a.created_at));
  async function logout(){const {error}=await supabase.auth.signOut();if(error)setError('Unable to sign out. Please try again.');}
  return <><header className="header"><a className="brand" href="#"><Aperture size={29}/> Lucas Presets<span className="brand-dot">.</span></a><nav aria-label="Main navigation"><a className="nav-active" href="#catalog">Library</a><a href="#how">How it works</a></nav><div className="account">{session?<><span className="email">{session.user.email}</span>{isAdmin&&<button className="text-button" onClick={()=>setShowAdmin(value=>!value)} aria-expanded={showAdmin} aria-controls="admin">{showAdmin?'Close admin':'Admin'}</button>}<button className="text-button" onClick={logout} title="Sign out"><LogOut size={18}/><span>Sign out</span></button></>:<><button className="text-button" onClick={()=>setAuth('login')}>Sign in</button><button className="button small" onClick={()=>setAuth('signup')}>Create an account <ArrowUpRight size={16}/></button></>}</div></header>
  <main>{isAdmin&&showAdmin&&<Admin assets={assets} onChange={()=>{setSelected(null);setRefresh(v=>v+1);}}/>}<section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> FOR CREATORS. ALWAYS FREE.</div><h1>Your story.<br/>New <em>colors.</em></h1><p>Discover LUTs and presets that give your photos<br className="desktop-break"/> and videos a signature look. Create, share, inspire.</p><a className="button hero-button" href="#catalog">Explore the library <ArrowRight size={18}/></a><div className="hero-note"><span><Check size={14}/> 100% free</span><span><Check size={14}/> For photos and videos</span></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=90" alt="A mountain cabin beside a peaceful lake"/><div className="image-grain"/><span className="image-caption">SMALL CHANGE. BIG MOOD.</span><div className="image-label"><span className="live-dot"/> THE GOLDEN LOOK <span>01 / 06</span></div></div></section>
  <div className="feature-strip"><span><Film size={19}/> LUTs for your videos</span><span><Camera size={19}/> Presets for your photos</span><span><MessageCircle size={19}/> A community of creators</span><span><Download size={19}/> Free downloads</span></div>
  <section id="catalog" className="catalog"><div className="section-top"><div><div className="eyebrow muted">FIND YOUR STYLE</div><h2>Your inspiration library<span>.</span></h2><p>One click can change the whole story.</p></div><span className="item-count">{assets.length} {supabase?'items in the library':'demo items'}</span></div>
  {!supabase&&<div className="notice">Demo mode · Explore sample looks. Sign-up, downloads, ratings and comments are currently unavailable.</div>}
  {supabase&&!session&&<div className="notice download-notice"><Lock size={18}/><span>Browse every LUT and preset for free. <strong>Sign in to download.</strong></span><button className="text-button" onClick={()=>setAuth('signup')}>Create a free account <ArrowRight size={16}/></button></div>}<div className="toolbar"><div className="tabs" role="group" aria-label="Content type">{[['all','All'],['lut','Video LUTs'],['preset','Photo presets']].map(([value,label])=><button key={value} className={type===value?'active':''} onClick={()=>setType(value)}>{value==='lut'?<Film size={16}/>:value==='preset'?<Camera size={16}/>:null}{label}</button>)}</div><label className="search"><Search size={18}/><input aria-label="Search the library" placeholder="Find your next look…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="select-wrap"><SlidersHorizontal size={16}/><select aria-label="Style" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c} value={c}>{categoryLabel(c)}</option>)}</select></label></div>
  <div className="results-top"><span>{visible.length} results</span><label>Sort by: <select aria-label="Sort order" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Newest</option>{session&&<option value="rating">Top rated</option>}<option value="name">Name</option></select></label></div>
  {error&&<div role="alert" className="notice error">{error}<button onClick={()=>setRefresh(v=>v+1)}>Try again</button></div>}
  {!ready||loading?<div className="empty">Loading the library…</div>:visible.length?<div className="grid">{visible.map(a=>{const s=stats(a.id);return <button className="card" key={a.id} onClick={()=>setSelected(a)}><div className="card-image"><img loading="lazy" src={a.image_url} alt={a.title}/><span className={`badge ${a.kind}`}>{a.kind==='lut'?<Film size={12}/>:<Camera size={12}/>} {a.kind==='lut'?'VIDEO LUT':'PHOTO PRESET'}</span>{a.featured&&<span className="featured">Lucas Presets pick</span>}<span className="card-open"><ArrowUpRight size={20}/></span></div><div className="card-body"><div className="card-heading"><h3>{a.title}</h3><span className="free">FREE</span></div><p>{categoryLabel(a.category)} <span>·</span> {a.format}</p><div className="card-bottom"><span className="rating"><Star size={14}/>{supabase&&!session?'Sign in to rate':s.count?s.average.toFixed(1):'No ratings yet'}{s.count>0&&<small>({s.count})</small>}</span><span className="discover">View <ArrowRight size={14}/></span></div>{supabase&&!session&&<div className="card-download-note"><Lock size={12}/>Sign in to download</div>}</div></button>;})}</div>:<div className="empty"><h3>{assets.length?'No matching looks found.':'The library is ready for its first looks.'}</h3><p>{assets.length?'Try another search or adjust your filters.':(isAdmin?'Add your first LUT or preset in Admin.':'New LUTs and presets are coming soon.')}</p>{assets.length>0&&<button className="text-button" onClick={()=>{setQuery('');setCategory(categories[0]);setType('all');}}>Clear filters</button>}</div>}
  </section><section id="how" className="how"><div><div className="eyebrow muted">MORE CREATING. LESS SEARCHING.</div><h2>From inspiration to<br/>your next look.</h2></div><div className="steps">{[['01','Find your style','Browse every LUT and preset. No account needed.'],['02','Join the community','Create a free account to download your favorite looks.'],['03','Download and create','Download from Google Drive. Leave a rating and share your experience.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section></main>
  <footer><a className="brand" href="#"><Aperture size={23}/> Lucas Presets.</a><p>Color brings us together. Create together.</p><span>© {new Date().getFullYear()} Lucas Presets</span></footer>
  {auth&&<AuthModal mode={auth} setMode={setAuth} close={()=>setAuth(null)}/>}
  {selected&&!auth&&<Detail asset={assets.find(asset=>asset.id===selected.id)||selected} session={session} close={()=>setSelected(null)} stats={stats(selected.id)} onRating={()=>setRefresh(v=>v+1)} onSignIn={()=>setAuth('login')} onSignUp={()=>setAuth('signup')}/>}
  </>;
}
function Modal({close,children,label}) {
  const ref=React.useRef(null);
  useEffect(()=>{const previous=document.activeElement;const el=ref.current;el.focus();const trap=e=>{if(e.key!=='Tab')return;const focusable=[...el.querySelectorAll('button,input,textarea,a[href],select')].filter(x=>!x.disabled);if(!focusable.length){e.preventDefault();return;}const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===el)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===el)){e.preventDefault();first.focus();}};el.addEventListener('keydown',trap);return()=>{el.removeEventListener('keydown',trap);previous?.focus();};},[]);
  return <div className="overlay" onClick={e=>{if(e.target===e.currentTarget)close();}}><section ref={ref} tabIndex={-1} className="modal" role="dialog" aria-modal="true" aria-label={label}><button className="close" onClick={close} aria-label="Close"><X size={22}/></button>{children}</section></div>;
}
function AuthModal({mode,setMode,close}) {
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setMessage('');if(!supabase){setMessage('Sign-in and sign-up are currently unavailable in demo mode.');return;}setBusy(true);
    try{let result;if(mode==='signup')result=await supabase.auth.signUp({email,password,options:{data:{display_name:name.trim()},emailRedirectTo:window.location.origin}});else result=await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(mode==='signup'&&!result.data.session)setMessage('Check your inbox and confirm your email address. Then you can sign in.');else close();}catch(err){setMessage(err.code==='invalid_credentials'?'Your email or password is incorrect.':err.code==='email_not_confirmed'?'Confirm your email address using the link in your inbox first.':err.code==='user_already_exists'?'An account with this email already exists. Please sign in.':'Something went wrong. Check your details and try again.');}finally{setBusy(false);}
  }
  function switchMode(){setMode(mode==='signup'?'login':'signup');setMessage('');}
  return <Modal close={close} label={mode==='signup'?'Sign up':'Sign in'}><div className="modal-logo"><Aperture size={32}/></div><div className="eyebrow muted">YOUR SPACE TO CREATE</div><h2>{mode==='signup'?'Start a new chapter.':'Welcome back.'}</h2><p className="modal-intro">An entire library. Fresh looks. One creative community.</p><form onSubmit={submit}>{mode==='signup'&&<label>Display name<input required maxLength={40} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></label>}<label>Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" required minLength={mode==='signup'?8:1} autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='signup'?'At least 8 characters':'Your password'}/></label>{message&&<p className="notice" role="status">{message}</p>}<button className="button full" disabled={busy}>{busy?'Please wait…':mode==='signup'?'Create a free account':'Sign in'}<ArrowRight size={17}/></button></form><p className="auth-switch">{mode==='signup'?'Already have an account?':'New here?'} <button onClick={switchMode}>{mode==='signup'?'Sign in':'Sign up'}</button></p></Modal>;
}
function Detail({asset,session,close,stats,onRating,onSignIn,onSignUp}) {
  const [comments,setComments]=useState([]),[text,setText]=useState(''),[score,setScore]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!!supabase&&!!session);
  useEffect(()=>{if(!supabase||!session)return;let active=true;Promise.all([supabase.from('comments').select('id,user_id,body,created_at,profiles(display_name)').eq('asset_id',asset.id).order('created_at',{ascending:false}),supabase.from('ratings').select('score').eq('asset_id',asset.id).eq('user_id',session.user.id).maybeSingle()]).then(([c,r])=>{if(!active)return;setLoading(false);if(c.error||r.error)setMessage('Unable to load comments or ratings. Please try again.');else{setComments(c.data);setScore(r.data?.score||0);}});return()=>{active=false;};},[asset.id,session]);
  async function rate(value){if(!supabase||!session){setMessage('Sign in to rate this look. Ratings are unavailable in demo mode.');return;}setBusy(true);setMessage('');const {error}=await supabase.from('ratings').upsert({asset_id:asset.id,user_id:session.user.id,score:value},{onConflict:'asset_id,user_id'});setBusy(false);if(error)setMessage('Unable to save your rating. Please try again.');else{setScore(value);onRating();}}
  async function comment(e){e.preventDefault();if(!supabase||!session){setMessage('Sign in to leave a comment. Comments are unavailable in demo mode.');return;}if(!text.trim())return;setBusy(true);setMessage('');const {data,error}=await supabase.from('comments').insert({asset_id:asset.id,user_id:session.user.id,body:text.trim()}).select('id,user_id,body,created_at,profiles(display_name)').single();setBusy(false);if(error)setMessage('Unable to post your comment. Please try again.');else{setComments(c=>[data,...c]);setText('');}}
  async function remove(id){setBusy(true);const {error}=await supabase.from('comments').delete().eq('id',id).eq('user_id',session.user.id);setBusy(false);if(error)setMessage('Unable to delete your comment. Please try again.');else setComments(c=>c.filter(x=>x.id!==id));}
  const validDownload=(()=>{try{const u=new URL(asset.download_url);return u.protocol==='https:'&&u.hostname==='drive.google.com';}catch{return false;}})();
  return <Modal close={close} label={asset.title}><img className="detail-image" src={asset.image_url} alt={asset.title}/><div className="eyebrow muted">{asset.kind==='lut'?'VIDEO LUT':'PHOTO PRESET'} · {asset.format}</div><h2>{asset.title}</h2><p className="modal-intro">{asset.description}</p><p className="compatibility">Compatible with: {asset.software}</p>{supabase&&!session?<div className="notice"><strong>Sign in to download this look.</strong><p>Create a free account to download LUTs and presets.</p><div className="admin-actions"><button className="button small" onClick={onSignIn}>Sign in to download <Lock size={16}/></button><button className="text-button" onClick={onSignUp}>Create a free account</button></div></div>:session&&validDownload?<a className="button full" href={asset.download_url} target="_blank" rel="noopener noreferrer">Download from Google Drive <Download size={18}/></a>:<div className="notice">{supabase?'A download link is not available yet.':'This demo look does not include a download.'}</div>}<div className="detail-rating"><h3>How do you like this look?</h3><div className="stars" aria-label="Your rating">{[1,2,3,4,5].map(n=><button key={n} disabled={busy||!session||!supabase} aria-label={`Rate ${n} out of 5`} aria-pressed={score===n} onClick={()=>rate(n)}><Star size={25} fill={n<=score?'currentColor':'none'}/></button>)}<span>{supabase&&!session?'Sign in to view ratings':stats.count?`${stats.average.toFixed(1)} / 5 · ${stats.count} ratings`:'No ratings yet'}</span></div></div>{session&&<><h3>Comments <span className="muted">({comments.length})</span></h3>{message&&<p className="notice" role="status">{message}</p>}<form onSubmit={comment}><label className="sr-only" htmlFor="comment">Your comment</label><textarea id="comment" required maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder="Share your experience…"/><button className="button small" disabled={busy||!text.trim()}>Post comment <ArrowRight size={15}/></button></form><div className="comments">{loading?<p>Loading comments…</p>:comments.length?comments.map(c=><article key={c.id}><div><strong>{c.profiles?.display_name||'Creator'}</strong><time>{new Date(c.created_at).toLocaleDateString('en-US')}</time></div><p>{c.body}</p>{c.user_id===session?.user.id&&<button className="text-button" disabled={busy} onClick={()=>remove(c.id)}>Delete</button>}</article>):<p className="muted">No comments yet. Be the first to share your experience.</p>}</div></>}{supabase&&!session&&<p className="notice">Sign in to read comments, leave a rating and share your experience.</p>}</Modal>;
}
createRoot(document.getElementById('root')).render(<App/>);
